### ISSUE TITLE
Error while running drugZ_w_modules.py

### ISSUE THREAD

**Issue by mj163163** [hart-lab/drugz#7]
Hi Medina,
When I was running  drugZ_w_modules.py, I got the error information:

 File "drugZ_w_modules.py", line 347, in drugZ_analysis
    fold_change =pd.concat(fold_changes, axis=1, sort=False)
TypeError: concat() got an unexpected keyword argument 'sort'

It is OK when I was using DrugZ.py

Best,
Wenjun

**Comment by mcolic** [comment]
That's due python version. 
DrugZ.py is python 2, while drugZ_w_modules.py is python 3.
I will update the FDR calculation in drugZ.py in a bit, and you can keep using drugZ.py then.

**Comment by mj163163** [comment]
Thanks. Problem is solved after I upgrading the pandas to 0.24.

**Comment by mcolic** [comment]
Great! Happy to hear it's solved.

**Comment by liuyin111** [comment]
The same error is still existing.

INFO:__main__:Initiating analysis
INFO:__main__:Loading the read count matrix
INFO:__main__:Normalizing read counts
INFO:__main__:Calculating raw fold change for replicate 1
INFO:__main__:Caculating smoothed Epirical Bayes estimates of stdev for replicate 1
INFO:__main__:Caculating guide-level Zscores for replicate 1
Traceback (most recent call last):
  File "drugz.py", line 478, in <module>
    main()
  File "drugz.py", line 475, in main
    drugZ_analysis(args)
  File "drugz.py", line 458, in drugZ_analysis
    fold_change =pd.concat(fold_changes, axis=1, sort=False)
TypeError: concat() got an unexpected keyword argument 'sort'
